- name: Add info for branches
  shell: 'echo "{{ system_watch_git_header_branches }}" > {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt'
  with_items: '{{ system_watch_git_status_repos }}'
  changed_when: false

- name: Log current git branches
  shell: "git --work-tree={{ instance.path }} branch -a >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt"
  with_items: '{{ system_watch_git_status_repos }}'
  changed_when: false
  args:
    chdir: '{{ instance.path }}'

- name: Add info for change status
  shell: 'echo "{{ system_watch_git_header_changes }}" >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt'
  with_items: '{{ system_watch_git_status_repos }}'
  changed_when: false

- name: Log git status
  shell: "git --work-tree={{ instance.path }} status -s >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt"
  with_items: '{{ system_watch_git_status_repos }}'
  changed_when: false
  args:
    chdir: '{{ instance.path }}'
