- name: Log drupal metadata
  shell: "{{ drush_path }} @{{ instance.name }} pm-list > {{ system_watch_log_dir }}/drupal_modules_{{ instance.name }}.txt"
  changed_when: false

- name: Log drupal git status
  shell: "git status > {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt"
  changed_when: false
  args:
    chdir: '{{ instance.dir }}'
