- name: Set redmine_dir variable
  set_fact: redmine_dir="{{ instance.dir | default("/srv/" + instance.name) }}"

- name: Set redmine_rails_env variable
  set_fact: redmine_rails_env="{{ instance.rails_env | default(rails_env) }}"

- name: Log redmine gem metadata - {{ instance.name }}
  become: yes
  become_user: '{{ instance.name }}'
  shell: bash -lc "gem list > /var/run/{{ instance.name }}/redmine_info.txt"
  args:
    chdir: '{{ redmine_dir }}'
  changed_when: false

- name: Log redmine metadata - {{ instance.name }}
  become: yes
  become_user: '{{ instance.name }}'
  shell: bash -lc "bin/about >> /var/run/{{ instance.name }}/redmine_info.txt"
  args:
    chdir: '{{ redmine_dir }}'
  environment:
    RAILS_ENV: '{{ redmine_rails_env }}'
  changed_when: false

- name: Copy redmine metadata to git - {{ instance.name }}
  synchronize:
    mode: pull
    src: /var/run/{{ instance.name }}/redmine_info.txt
    dest: "{{ system_watch_log_dir }}/{{ '' if instance.name=='redmine' else 'redmine_' }}{{ instance.name }}.txt"
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"

- name: Add redmine info for branches - {{ instance.name }}
  shell: 'echo "Branches:" > {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt'
  changed_when: false

- name: Log current redmine git branches - {{ instance.name }}
  shell: "git --work-tree={{ redmine_dir }} branch -a >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt"
  changed_when: false
  args:
    chdir: '{{ redmine_dir }}'

- name: Add empty line - {{ instance.name }}
  shell: 'echo "" >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt'
  changed_when: false

- name: Add redmine info for change status - {{ instance.name }}
  shell: 'echo "Changes:" >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt'
  changed_when: false

- name: Log redmine git status - {{ instance.name }}
  shell: "git --work-tree={{ redmine_dir }} status -s >> {{ system_watch_log_dir }}/git_status_{{ instance.name }}.txt"
  changed_when: false
  args:
    chdir: '{{ redmine_dir }}'
